### ISSUE TITLE
update externals

### ISSUE THREAD

**Issue by vrodin** [tihmstar/Otakutachi#1]
Project has building problems, 

*/Otakutachi/src/msc_disk.cpp: In function 'void cb_newFile(const char*, const char*, uint32_t, uint32_t)':
*/Otakutachi/src/msc_disk.cpp:28:11: error: 'class tihmstar::EmuFATFS<35, 1024>' has no member named 'addFileDynamic'
   28 |   gEmuFat.addFileDynamic(filename, NULL, fileSize, clusterLocation, cb_readLFSFile, cb_writeLFSFile);
      |           ^~~~~~~~~~~~~~
*/Otakutachi/src/msc_disk.cpp: In function 'void init_fakefatfs()':
*/Otakutachi/src/msc_disk.cpp:88:35: error: invalid conversion from 'void (*)(const char*, const char*, uint32_t, uint32_t)' {aka 'void (*)(const char*, const char*, long unsigned int, long unsigned int)'} to 'tihmstar::EmuFATFSBase::cb_newFile' {aka 'void (*)(const char*, const char*, long unsigned int)'} [-fpermissive]
   88 |   gEmuFat.registerNewfileCallback(cb_newFile);
      |                                   ^~~~~~~~~~
      |                                   |
      |                                   void (*)(const char*, const char*, uint32_t, uint32_t) {aka void (*)(const char*, const char*, long unsigned int, long unsigned int)}
In file included from*/Otakutachi/src/msc_disk.cpp:2:
*/Otakutachi/include/EmuFATFS.hpp:75:45: note:   initializing argument 1 of 'void tihmstar::EmuFATFSBase::registerNewfileCallback(tihmstar::EmuFATFSBase::cb_newFile)'
   75 |     void registerNewfileCallback(cb_newFile f_newfilecb);
      |                                  ~~~~~~~~~~~^~~~~~~~~~~
make[2]: *** [CMakeFiles/Otakutachi.dir/build.make:104: CMakeFiles/Otakutachi.dir/src/msc_disk.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1532: CMakeFiles/Otakutachi.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by tihmstar** [comment]
whoops sorry, i pushed https://github.com/tihmstar/EmuFATFS/commit/cb5ab6d1b95c75188c0ac7831be191f81f8f4188 and now it should work fine
